### ISSUE TITLE
Can you help me to fix this?

### ISSUE THREAD

**Issue by peter9811** [farag2/Office#8]
![image](https://user-images.githubusercontent.com/22783445/185696252-3b24c0e9-bdaf-4025-a624-6f64aa4cbc28.png)

Autosave is not available.
The file could not be saved
automatically due to the configuration of
privacy. To prevent them from being lost
changes, save the file with the file >
save.

**Comment by farag2** [comment]
Well, I think it's not related with my script, but I may help. Could you write to our Discord group? I will need a remote access via AnyDesk. I see only this way out.

**Comment by farag2** [comment]
https://discord.gg/sSryhaEv79

**Comment by peter9811** [comment]
Oh yeah. Sure, I know it's something personal, but I don't know if that functionality can be activated for offline saving, because I think it only works with OneDrive and I've really eliminated OneDrive with scripts and all that to have more speed and privacy on the PC

**Comment by farag2** [comment]
if you do not have an MS account, you cannot activate autosaving (I thought you had account) due to all files will be saved to cloud.

**Comment by farag2** [comment]
> all that to have more speed and privacy on the PC
You do not have neither speed, nor privacy: OneDrive doesn't overload OS (really, in 2022 with 32 GB of RAM?), privacy? how does it interact with it? Anyway, it's up to up uninstall it or not.

**Comment by peter9811** [comment]
Yes, I do, although I tend not to use it, but I would like the automatic saving to be offline, to save my files in the Documents folder
I don't know if it's possible and if it isn't, then nothing happens, haha. You could go back to MS Office 2019 or just ignore that functionality

**Comment by peter9811** [comment]
> 

My PC no are the top, only have 12 Gb RAM and I use Inventor and SolidWorks with i5 5th... Is not a powerful

**Comment by farag2** [comment]
> with i5 5th

meh :(

**Comment by farag2** [comment]
> I would like the automatic saving to be offline, to save my files in the Documents folder

It calls cloud saving man. MS won;t allow to autosave anything offline. It breaks strategy. really, I understand them)
