### ISSUE TITLE
Автоматизация скрипта

### ISSUE THREAD

**Issue by uffemcev** [farag2/Office#9]
Хотел бы предложить в будущих версиях скрипта Download.ps1 убрать в конце обращение к функции DownloadOffice. Мне кажется, было бы удобнее обращаться к данной функции через powershell\cmd с указанием конкретных параметров.

К примеру: powershell -command "& { . .\Download.ps1; DownloadOffice -Branch O365ProPlusRetail -Channel Current -Components Word, Excel, PowerPoint }"

Таким образом получится упростить процесс автоматической установки на множество ПК без редактирования самого скрипта. Спасибо вам за вашу работу, надеюсь вы рассмотрите моё предложение! :)

**Comment by farag2** [comment]
Справедливо. Завтра сделаю. Эх, вы, ламеры))

**Comment by uffemcev** [comment]
> Справедливо. Завтра сделаю. Эх, вы, ламеры))

Так молниеносно ответили, спасибо вам большое!

**Comment by farag2** [comment]
Вроде, все.
